name: Release
on:
  push:
    tags: 
      - '*'

jobs:
  lint:
    uses: quenktechnologies/.github/.github/workflows/node-eslint.yml@master
  release:    
    uses: quenktechnologies/.github/.github/workflows/node-publish.yml@master
    secrets: inherit
