name: Release
on:
  push:
    tags: 
      - '*'

jobs:
  release:
    - uses: quenktechnologies/.github/.github/workflows/node-eslint.yml@master
    - uses: quenktechnologies/.github/.github/workflows/node-publish.yml@master
      secrets: inherit
