name: Test
on:
  push:
    branches: 
      - master

jobs:
  lint:
    uses: quenktechnologies/.github/.github/workflows/node-eslint.yml@master
  release:
    uses: quenktechnologies/.github/.github/workflows/node-build.yml@master
    secrets: inherit
